### ISSUE TITLE
Broken pipe with starttls

### ISSUE THREAD

**Issue by katyo** [stephank/tokio-smtp#4]
I have unexpected closing of connection by client when starttls is used.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: BrokenPipe, error: StringError("broken pipe") }', libcore/result.rs:945:5
```

This is my code:

```rust
extern crate futures;
extern crate tokio_core;
extern crate tokio_proto;
extern crate tokio_service;
extern crate tokio_smtp;

use futures::{Future};
use std::net::{ToSocketAddrs};
use tokio_core::reactor::{Core};
use tokio_proto::streaming::{Message};
use tokio_service::{Service};
use tokio_smtp::request::{ClientId, Request as SmtpRequest};
use tokio_smtp::client::{Client as SmtpClient};

fn main() {
    let mut core = Core::new().unwrap();
    let handle = core.handle();

    let client_id = ClientId::Domain("incognito.example.com".into());

    let client = SmtpClient::secure(client_id.clone(), "smtp.gmail.com".into()).unwrap();
    //let client = SmtpClient::insecure(client_id.clone());

    let addr = "smtp.gmail.com:25".to_socket_addrs().unwrap().next().unwrap();
    
    let f = client.connect(&addr, &handle)
        .and_then(|service| {
            service.call(Message::WithoutBody(SmtpRequest::Quit))
                .and_then(|response| {
                    println!("response {:?}", response);
                    Ok(())
                })
        });
    
    core.run(f).unwrap();
}
```

I added debug logging into library to see exchanging messages:

```
 DEBUG tokio_smtp::client > C: Message { message: Ehlo(Domain("incognito.example.com")), body: false }
 DEBUG tokio_smtp::client > C: Message { message: StartTls, body: false }
 DEBUG tokio_smtp::client > S: Message { message: Response { code: Code { severity: PositiveCompletion, category: Connections, detail: Detail(0) }, text: ["smtp.gmail.com ESMTP j74-v6sm1161811lfg.92 - gsmtp"] }, body: false }
 DEBUG tokio_smtp::client > S: Message { message: Response { code: Code { severity: PositiveCompletion, category: MailSystem, detail: Detail(0) }, text: ["smtp.gmail.com at your service, [188.19.36.111]", "SIZE 35882577", "8BITMIME", "STARTTLS", "ENHANCEDSTATUSCODES", "PIPELINING", "CHUNKING", "SMTPUTF8"] }, body: false }
 DEBUG tokio_smtp::client > S: Message { message: Response { code: Code { severity: PositiveCompletion, category: Connections, detail: Detail(0) }, text: ["2.0.0 Ready to start TLS"] }, body: false }
 DEBUG tokio_smtp::client > C: Message { message: Ehlo(Domain("incognito.example.com")), body: false }
 DEBUG tokio_smtp::client > S: Message { message: Response { code: Code { severity: PositiveCompletion, category: MailSystem, detail: Detail(0) }, text: ["smtp.gmail.com at your service, [188.19.36.111]", "SIZE 35882577", "8BITMIME", "AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH", "ENHANCEDSTATUSCODES", "PIPELINING", "CHUNKING", "SMTPUTF8"] }, body: false }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: BrokenPipe, error: StringError("broken pipe") }', libcore/result.rs:945:5
```

But when insecure connection is used all works as expected:

```
 DEBUG tokio_smtp::client > C: Message { message: Ehlo(Domain("incognito.example.com")), body: false }
 DEBUG tokio_smtp::client > S: Message { message: Response { code: Code { severity: PositiveCompletion, category: Connections, detail: Detail(0) }, text: ["smtp.gmail.com ESMTP o192-v6sm1173695lfe.38 - gsmtp"] }, body: false }
 DEBUG tokio_smtp::client > S: Message { message: Response { code: Code { severity: PositiveCompletion, category: MailSystem, detail: Detail(0) }, text: ["smtp.gmail.com at your service, [188.19.36.111]", "SIZE 35882577", "8BITMIME", "STARTTLS", "ENHANCEDSTATUSCODES", "PIPELINING", "CHUNKING", "SMTPUTF8"] }, body: false }
 DEBUG tokio_smtp::client > C: Message { message: Quit, body: false } // <~ my own message here
 DEBUG tokio_smtp::client > S: Message { message: Response { code: Code { severity: PositiveCompletion, category: Connections, detail: Detail(1) }, text: ["2.0.0 closing connection o192-v6sm1173695lfe.38 - gsmtp"] }, body: false }
response Message::WithoutBody(Response { code: Code { severity: PositiveCompletion, category: Connections, detail: Detail(1) }, text: ["2.0.0 closing connection o192-v6sm1173695lfe.38 - gsmtp"] })
```

**Comment by katyo** [comment]
As I see the break occurs after second handshake on established tls connection.
But it seems is non-trivial for me to understand what happens here.
I see only the closing of connection by client via network analyzer.

**Comment by katyo** [comment]
I enabled tokio-proto logs and now I see also error:

```
 ERROR tokio_proto::streaming::pipeline::client > pipeline error: invalid handshake
```

**Comment by katyo** [comment]
On the second time we do not need await for server opening message to check for ESMTP because we already connected and TLS session established.

**Comment by stephank** [comment]
Your PR fixed this, I think! :)
